### ISSUE TITLE
LOGSEVERE and LOGNOTICE will deprecated in kodi/python addons

### ISSUE THREAD

**Issue by phunkyfish** [jamontes/plugin.video.filmsforaction#1]
Please replace with LOGFATAL and LOGINFO. They will be removed in a couple of weeks.

PR: https://github.com/xbmc/xbmc/pull/18346
Forum Post: https://forum.kodi.tv/showthread.php?tid=353818

**Comment by jamontes** [comment]
Hi phunkyfish,

Thanks a lot for let me know. I'll summit a new PR to Matrix repo with the fix as soon as possible.

Best regards,

jamontes.

**Comment by phunkyfish** [comment]
Thanks!

**Comment by jamontes** [comment]
I close this issue still opened but long time ago solved in https://github.com/jamontes/plugin.video.filmsforaction/commit/1c119ea96fc56b527dbf95fe22e53fa970743e9f
Thanks a lot for your help and best regards,
jamontes.
