### ISSUE TITLE
Issue with Matrix

### ISSUE THREAD

**Issue by ltai0001** [jamontes/plugin.video.filmsforaction#2]
Issue with Kodi Matrix
Says “ Video type not supported”

**Comment by jamontes** [comment]
Hi Itai0001,

Many thanks for let me know.

I've found the problem is caused due to some website changes and I'll try to fix it as soon as possible on a maintenance release.

Many thanks for your help and best regards,

jamontes.

**Comment by jamontes** [comment]
Hi Itai0001,

I've fixed the problem and summited the changes with PR #3823 that has been accepted and merged so the add-on will be automatically updated on your plaftform in a few days hopefully.

Best regards,

jamontes.

**Comment by ltai0001** [comment]
thanks so much working great
